### ISSUE TITLE
Incorrect behaviour of "Matrix" keyword in the coupled case for current zgoubi version

### ISSUE THREAD

**Issue by marionvanwelde** [chernals/zgoubido#27]
The keyword "MATRIX" in the coupled case no longer works in the current version of ZGOUBI.
We can use the following element : 

'MATRIX' Matrix                                                                                              
1 11 PRINT coupled

An old version of zgoubi uses the coupled formalism while the current version uses the uncoupled formalism.

**Comment by marionvanwelde** [comment]
Fixed in Zgoubi

**Comment by chernals** [comment]
OK to close.
