### ISSUE TITLE
Incorrect placement of elements with integration zone

### ISSUE THREAD

**Issue by rtesse** [chernals/zgoubido#31]
The placement of the elements seem to be incorrect when we specify X_E or X_S of an element. The center of the element is moving depending on the value of X_E or X_S. Here is a minimal example:

```
import zgoubidoo
from zgoubidoo.commands import *
from zgoubidoo import ureg as _ureg

qf = Multipole('QF', XL=1*_ureg.m, B1=1 * _ureg.tesla)
qd = Multipole('QD', XL=1*_ureg.m, B1=-1 * _ureg.tesla)

zi = zgoubidoo.Input(name='FODO', line=[
    Objet2('BUNCH', BORO=k.brho),
    Proton(),
    qf,
    Drift(XL=1 * _ureg.m),
    qd,
    Drift(XL=1 * _ureg.m),
])

qf.X_E = 20 *_ureg.cm
qf.X_S = 20 *_ureg.cm

qd.X_E = 0 *_ureg.cm
qd.X_S = 0 *_ureg.cm

zi.survey(with_reference_trajectory=True, reference_kinematics=zgoubidoo.Kinematics(2 * _ureg.GeV))
zi.IL = 2
zi.XPAS = 2 * _ureg.cm

artist = zgoubidoo.vis.ZgoubidooPlotlyArtist()

artist.fig['layout']['xaxis']['title'] = "X (m)"
artist.fig['layout']['yaxis']['title'] = "Y (m)"
artist.fig['layout']['font']['size'] = 10


artist.plot_beamline(beamline=zi, with_frames=True, with_map=True)
artist.render()
```

As we can see in the figure below, the quadrupole starts at S = -0.2 meters. 

![issue-30](https://user-images.githubusercontent.com/26649180/127129111-5bdab234-957f-4ec3-a0c4-c939e0aeac80.png)

**Comment by marionvanwelde** [comment]
The error seems to come from the calculation of the entry_patched, exit, and exit_patched of a Cartesian magnet. Indeed, the frames are transformed by considering the X_E and X_S as an offset on the longitudinal axis (lines 173, 178, 197, 210, 214). However, the X_E and X_S do not represent element offsets but integration zones. Therefore, they can not modify the positioning of the elements to each other. They thus must not be taken into account in the calculation of the frames associated with the elements.

**Comment by chernals** [comment]
Non non, pas d’accord !

On Jul 27, 2021, at 14:20, marionvanwelde ***@***.***> wrote:

﻿

The error seems to come from the calculation of the entry_patched, exit, and exit_patched of a Cartesian magnet. Indeed, the frames are transformed by considering the X_E and X_S as an offset on the longitudinal axis (lines 173, 178, 197, 210, 214). However, the X_E and X_S do not represent element offsets but integration zones. Therefore, they can not modify the positioning of the elements to each other. They thus must not be taken into account in the calculation of the frames associated with the elements.

**Comment by marionvanwelde** [comment]
The error was that we took the XE into account before making the rotation; the rotation was thus around the integration zone.
To be sure of the frames that we use, we keep the entry_patched linked to the magnet, and we will create frames for the integration areas.
